;METADATA=(Diff=true, UseCommands=true)

[/Script/GameplayTags.GameplayTagsSettings]
ImportTagsFromConfig=True
WarnOnInvalidTags=True
ClearInvalidTags=False
AllowEditorTagUnloading=True
AllowGameTagUnloading=False
FastReplication=False
bDynamicReplication=False
InvalidTagCharacters="\"\',"
NumBitsForContainerSize=6
NetIndexFirstBitSegment=16
+GameplayTagList=(Tag="Library",DevComment="")
+GameplayTagList=(Tag="Library.Characters",DevComment="")
+GameplayTagList=(Tag="Library.Characters.Animals",DevComment="")
+GameplayTagList=(Tag="Library.Characters.Animated huamans",DevComment="")
+GameplayTagList=(Tag="Library.Characters.Posed humans",DevComment="")
+GameplayTagList=(Tag="Library.Cine",DevComment="")
+GameplayTagList=(Tag="Library.Cine.CameraRigRail",DevComment="")
+GameplayTagList=(Tag="Library.Cine.CineCamera",DevComment="")
+GameplayTagList=(Tag="Library.Light",DevComment="")
+GameplayTagList=(Tag="Library.Light.DirectionalLight",DevComment="Directional Light")
+GameplayTagList=(Tag="Library.Light.PointLight",DevComment="Point Light")
+GameplayTagList=(Tag="Library.Light.RectLight",DevComment="Rect Light")
+GameplayTagList=(Tag="Library.Light.SkyLight",DevComment="Sky Light")
+GameplayTagList=(Tag="Library.Light.SpotLight",DevComment="Spot Light")
+GameplayTagList=(Tag="Library.Object",DevComment="")
+GameplayTagList=(Tag="Library.Object.Home",DevComment="")
+GameplayTagList=(Tag="Library.Object.Home.Chairs1",DevComment="")
+GameplayTagList=(Tag="Library.Object.Home.TV",DevComment="")
+GameplayTagList=(Tag="Library.Object.Home.Sofa",DevComment="")
+GameplayTagList=(Tag="Library.Object.Home.Cabinet",DevComment="")
+GameplayTagList=(Tag="Library.Object.Home.Light",DevComment="")
+GameplayTagList=(Tag="Library.Object.Home.Lamp",DevComment="")
+GameplayTagList=(Tag="Library.Object.Home.CoffeeTable",DevComment="")
+GameplayTagList=(Tag="Library.Object.Home.PS5",DevComment="")
+GameplayTagList=(Tag="Library.Object.Home.ArmChair",DevComment="")
+GameplayTagList=(Tag="Library.Object.Primitives",DevComment="")
+GameplayTagList=(Tag="Library.Object.Primitives.Cone",DevComment="")
+GameplayTagList=(Tag="Library.Object.Primitives.Cube",DevComment="")
+GameplayTagList=(Tag="Library.Object.Primitives.Cylinder",DevComment="")
+GameplayTagList=(Tag="Library.Tool",DevComment="Tool")
+GameplayTagList=(Tag="Library.Tool.Memo",DevComment="Memo")
+GameplayTagList=(Tag="Library.Vegetation",DevComment="")
+GameplayTagList=(Tag="Library.Vegetation.Bushes",DevComment="")
+GameplayTagList=(Tag="Library.Vegetation.Rocks",DevComment="")
+GameplayTagList=(Tag="Library.Vegetation.Trees",DevComment="")
+GameplayTagList=(Tag="Library.Vehicles",DevComment="")
+GameplayTagList=(Tag="Library.Vehicles.Buses",DevComment="")
+GameplayTagList=(Tag="Library.Vehicles.Cars",DevComment="")
+GameplayTagList=(Tag="Library.Vehicles.Trucks",DevComment="")
+GameplayTagList=(Tag="Property.Light.Intensity",DevComment="")
+GameplayTagList=(Tag="Property.Light.Color",DevComment="")
+GameplayTagList=(Tag="Property.Material.SetScalar",DevComment="")
+GameplayTagList=(Tag="Property.Material.SetSlot",DevComment="")
+GameplayTagList=(Tag="Property.Material.SetVector",DevComment="")
+GameplayTagList=(Tag="Property.Mesh.Static",DevComment="")

